# Generated by Django 5.1.5 on 2025-02-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttime',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='districttime',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
