# Generated by Django 5.1.5 on 2025-02-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_category_surah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
