# Generated by Django 5.1.5 on 2025-02-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='districttime',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districttime',
            name='time_difference',
            field=models.IntegerField(editable=False),
        ),
    ]
